name: Build website and deploy with Docker

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  IMAGE_VERSION: ${{ github.sha }}

jobs:
  build-docker-image:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: |
            ghcr.io/thirty-degrees/homepage:${{ env.IMAGE_VERSION }}
            ghcr.io/thirty-degrees/homepage:latest
          build-args: |
            VERSION=alpine
          platforms: linux/arm64
          cache-from: type=registry,ref=ghcr.io/thirty-degrees/homepage:buildcache
          cache-to: type=registry,ref=ghcr.io/thirty-degrees/homepage:buildcache,mode=max

  trigger-deployment:
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Trigger image update in Calfur/calfur-dev
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_PAT_ACTIONS_TRIGGER }}
          repository: Calfur/calfur-dev
          event-type: new-thirty-degrees-homepage-image
          client-payload: '{"image_version": "${{ env.IMAGE_VERSION }}"}' 
